; Copyright (c) 2025 Good Night, Good Morning and contributors (see Contributors.md)
; Licensed under the MIT License. See the LICENSE file in the project root for details.

#lang racket

(provide initial-symbol-table)
(provide lookup)
(provide last-index-of)
(provide builtins)

(define builtins
  '(("+" "plus") ("-" "subtract")
                 ("*" "multiply")
                 ("/" "division")
                 ("not" "not")
                 ("char<=?" "char_le")
                 ("char>=?" "char_ge")
                 ("cons" "list_cons")
                 ("list" "list_constructor")
                 ("=" "equals")
                 ("eq?" "equals")
                 ("equal?" "equals")
                 ("null?" "is_null")
                 ("member" "member")
                 ("car" "car")
                 ("cdr" "cdr")
                 ("char->integer" "char_to_int")
                 ("string->list" "string_to_list")
                 ("get-args" "args")
                 ("displayln" "println")
                 ("<" "less")
                 (">" "greater")
                 ("error" "failfast")
                 ("pair?" "is_pair")
                 ("list->string" "list_to_string")
                 ("string-append" "string_append")
                 ("format" "format")
                 ("cadr" "cadr")
                 ("caddr" "caddr")
                 ("cddr" "cddr")
                 ("cddadr" "cddadr")
                 ("cdadr" "cdadr")
                 ("caadr" "caadr")
                 ("caar" "caar")
                 ("cdar" "cdar")
                 ("cdddr" "cdddr")
                 ("cadddr" "cadddr")
                 ("write-file" "write_file")
                 ("read-file" "read_file")))

(define (initial-symbol-table)
  (cons (map car builtins) '()))

(define (last-index-of l target current index)
  (if (null? l)
      current
      (let ([head (car l)]
            [rest (cdr l)])
        (if (equal? head target)
            (last-index-of rest target (list index) (+ index 1))
            (last-index-of rest target current (+ index 1))))))

(define (lookup symbol table level)
  (if (null? table)
      (error (format "Symbol '~a' is not found" symbol))
      (let ([result (last-index-of (car table) symbol '() 0)])
        (if (null? result)
            (lookup symbol (cdr table) (+ level 1))
            (cons level result)))))
